filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/user-service/*.log
    tags: ["user-service"]

  - type: log
    enabled: true
    paths:
      - /var/log/order-service/*.log
    tags: ["order-service"]

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
