logging:
  file:
    name: /app/logs/order/order-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: info

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
